### PR TITLE
Update weth strat withdraw logic

### PR DESCRIPTION
**Pull request by Byron-McKeeby**

### CODE REVIEW

**Comment by breadforthepeople** [comment]
Thank you for the fix. We have created a test for the strategy on mainnet fork, and it works well.

**Comment by Byron-McKeeby** [comment]
For `redeemMaximum` should we instead query the market for available cash and then redeem exactly that amount? That behavior would _not_ redeem all crWETH (there is no situation in which we can guarantee total redemption). But it _would_ redeem the maximum amount of crWETH, which feels like the best behavior

**Comment by breadforthepeople** [comment]
This seems like a reasonable solution. Can you please add this?

**Comment by Byron-McKeeby** [comment]
> This seems like a reasonable solution. Can you please add this?

Added

**Review by breadforthepeople — APPROVED** [review]

**Pull request merged**
